export const HOME_BANNER="widgets.home-banner"
export const HOME_SERVICES="widgets.home-services"
export const HOME_DOCTORS="widgets.home-doctors"
export const HOME_STATS="widgets.home-stat"
export const HOME_ABOUT="widgets.home-about"
export const HOME_CHOOSE="widgets.home-choose"
export const HOME_BLOGS="widgets.home-blogs"
export const HOME_SPEC="widgets.home-spec"
export const HOME_FAQ="widgets.home-faq"
export const CEO_MESSAGE="widgets.ceo-message"
export const INNER_BANNER="widgets.inner-banner"
export const BLOG_LISTING="widgets.blog-listing"
export const FEATURED_BLOGS="widgets.featured-blogs"
export const BASHAR_DEMO = "widgets.bashar-demo";
export const DEMO_HERO_WIDGET = "widgets.demo-hero-widget";
export const DEMO_STAT = "widgets.demo-stat";
export const DEMO_ABOUT = "widgets.demo-about";
export const DETAIL_WIDGET = "widgets.detail-widget";
export const FEATURE_BLOGS = "widgets.feature-blogs";
export const DOCTORS_CONTENT = "widgets.doctors-content";
export const DOCTORS_DETAIL = "widgets.doctors-detail";
export const DOCTORS_SINGLE_BANNER = "widgets.doctors-single-banner";
export const HOME_TESTIMONIALS = "widgets.home-testimonials";
export const HOME_CLIENTS = "widgets.home-clients";
export const CTA_SECTION = "widgets.cta-section";
export const CONTENT_SEC = "widgets.content-sec";
export const SERVICE_ABOUT = "widgets.service-about";
export const SERVICE_BANNER = "widgets.service-banner";
export const PACKAGE_WIDGET = "widgets.package-widget";
export const PACKAGE_LISTING = "widgets.package-listing";
export const CONTACT_BANNER = "widgets.contact-banner";
export const CONTACT_DETAILS = "widgets.contact-details";
export const SERVICE_LISTING = "widgets.service-listing";