  
import "./globals.css";
import Header from "@/components/Header";
import GlobalProviders from "@/components/GlobalProviders";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import nextFetch from "@/utils/nextFetch";
import { GLOBAL } from "@/constants/apiRoutes";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["variable"],
});
export const metadata = {
  title: "UDF | Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await nextFetch(GLOBAL);
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${dmSans.variable}`}>
        <GlobalProviders>
          <Header data={data?.data} />
          {children}
          <Footer data={data?.data} />
          <Toaster />
        </GlobalProviders>
      </body>
    </html>
  );
}
