  
import "./globals.css";
import Header from "@/components/Header";
import GlobalProviders from "@/components/GlobalProviders";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import nextFetch from "@/utils/nextFetch";
import { GLOBAL } from "@/constants/apiRoutes";
import { Lato , DM_Serif_Display} from "next/font/google";


const dmSans = Lato({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["300", "400", "700"],
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-dm-serif",
  weight: ["400"],
});


// export const metadata = {
//   title: "Calladoc | Home page",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
  const data = await nextFetch(GLOBAL);
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${dmSans.variable} ${dmSerif.variable}`}>
        <GlobalProviders>
          <Header data={data?.data} />
          {children}
          <Footer data={data?.data} />
          <Toaster />
        </GlobalProviders>
  

      </body>
    </html>
  );
}
